### ISSUE TITLE
Zero-shot transfer

### ISSUE THREAD

**Issue by nischalkhanal123** [Aradhye2002/EcoDepth#13]
Excellent work and impressive results.

I have a question about the quantitative results for zero-shot transfer. To get the results on unseen datasets, did you use the trained NYUv2 model with best_rmse.ckpt and train it again for one more epoch using those unseen datasets? 

Thank you

**Comment by Aradhye2002** [comment]
Hey @nischalkhanal123, of course not. The datasets are completely unseen. Finetuning on the unseen datasets would defeat the purpose of zero-shot transfer. We only train on NYUv2 and run inference on the unseen datasets.
