### ISSUE TITLE
Unable to open link for stable-diffusion

### ISSUE THREAD

**Issue by water221** [Aradhye2002/EcoDepth#17]
It's a great job, I want to do infer, but when I click on the link to download stable-diffusion-v1-5 at [here](https://github.com/Aradhye2002/EcoDepth/tree/main?tab=readme-ov-file#pretrained-models) the 404 interface appears, Dear author, can you redefine the link to stable-diffusion when you have time, and can you explain how stable-diffusion works, or why you set `PYTHONPATH="$(dirname $0)/..":"$(dirname $0)/../stable-diffusion":$PYTHONPATH \` in the train_nyu.sh file 
![image](https://github.com/user-attachments/assets/c5f80a57-50e7-4de3-9818-4fafe967b018)

**Comment by Aradhye2002** [comment]
Hi @water221, thank you for pointing out the broken link. I have updated the link, which now points to the Huggingface repository containing the `v1-5-pruned-emaonly.ckpt` checkpoint. Please download it and try again.

Regarding understanding Stable Diffusion, you can refer to the [Stable Diffusion GitHub repository](https://github.com/CompVis/stable-diffusion), where you'll find an in-depth explanation and code examples for usage. Let me know if you have any specific questions about how it is used in ECoDepth.

For your last question, let's break down the bash statement `PYTHONPATH="$(dirname $0)/..":"$(dirname $0)/../stable-diffusion":$PYTHONPATH`:

PYTHONPATH is an environment variable that tells Python which paths to search when you try to import a module or package.
The standard way of specifying the PYTHONPATH is as `PYTHONPATH=<path 1>:<path 2>:...:$PYTHONPATH`, where `<path 1>` is the path with the highest priority for the import manager to search, and so on. It is common practice to add PYTHONPATH at the end to retain the existing paths already present in the PYTHONPATH variable.
When you call the bash script, `$0` contains the 0th argument's name, which in this case would be the path to the script you are executing.
dirname is a bash utility that extracts the directory containing the file passed as an argument to dirname. It is used as `$(dirname <path/to/file>)`, where `<path/to/file>` is the path to a file for which you want to find the name of the enclosing directory.
Putting everything together, `$(dirname $0)/..` is the path to the parent directory of the directory containing the bash file, and `$(dirname $0)/../stable-diffusion` is the path to the stable-diffusion directory, which is present in the parent directory's parent.
