### ISSUE TITLE
train.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by 942411526** [Aradhye2002/EcoDepth#2]
bash train_kitti.sh
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
/home/yx/miniconda3/envs/ecodepth/lib/python3.11/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
usage: train.py [-h] [--exp_name EXP_NAME] [--gpu_or_cpu GPU_OR_CPU] [--data_path DATA_PATH]
                [--dataset {nyudepthv2,kitti,imagepath,vkitti,sunrgbd,ibims,diode_indoors_val,hypersim,vkitti2,diode_outdoor,DDAD,DIML}] [--batch_size BATCH_SIZE] [--workers WORKERS]
                [--max_depth MAX_DEPTH] [--min_depth MIN_DEPTH] [--max_depth_eval MAX_DEPTH_EVAL] [--min_depth_eval MIN_DEPTH_EVAL] [--do_kb_crop DO_KB_CROP]
                [--kitti_crop {garg_crop,eigen_crop}] [--pretrained PRETRAINED] [--drop_path_rate DROP_PATH_RATE] [--use_checkpoint USE_CHECKPOINT] [--num_deconv NUM_DECONV]
                [--num_filters NUM_FILTERS [NUM_FILTERS ...]] [--deconv_kernels DECONV_KERNELS [DECONV_KERNELS ...]] [--flip_test] [--no_of_classes NO_OF_CLASSES] [--vit_model VIT_MODEL]
                [--num_of_diffusion_step NUM_OF_DIFFUSION_STEP] [--eigen_crop_in_dataloader_itself_for_nyu EIGEN_CROP_IN_DATALOADER_ITSELF_FOR_NYU] [--use_right USE_RIGHT] [--cutflip CUTFLIP]
                [--variance_focus VARIANCE_FOCUS] [--epochs EPOCHS] [--max_lr MAX_LR] [--min_lr MIN_LR] [--weight_decay WEIGHT_DECAY] [--layer_decay LAYER_DECAY] [--crop_h CROP_H]
                [--crop_w CROP_W] [--log_dir LOG_DIR] [--val_freq VAL_FREQ] [--pro_bar PRO_BAR] [--model_save_freq MODEL_SAVE_FREQ] [--validate_on_kitti_also VALIDATE_ON_KITTI_ALSO]
                [--print_freq PRINT_FREQ] [--save_last_model] [--resume_from RESUME_FROM] [--save_depths_gray] [--save_depths_color] [--learning_rate_schedule LEARNING_RATE_SCHEDULE]
                [--gradient_accumulation GRADIENT_ACCUMULATION] [--log_in_wandb LOG_IN_WANDB] [--finetune_on_another_dataset FINETUNE_ON_ANOTHER_DATASET]
                [--pretrained_ckpt_path PRETRAINED_CKPT_PATH]
train.py: error: unrecognized arguments: --reg_loss_abs_of_embed False --vit_trainable False --use_cross_attn_of_unet False --kitti_split_to_half --trainable_bins False --bins_from_coarsest_res False --per_pixel_bin_prediction False --use_text_adapter True --pixelshuffle_decoder True

**Comment by Aradhye2002** [comment]
I have updated train_kitti.sh. Please take a look. It seems there were some stray arguments that we forgot to remove from the config file before uploading.
