### ISSUE TITLE
The test-simple python script

### ISSUE THREAD

**Issue by wangjiyuan9** [Aradhye2002/EcoDepth#3]
Hi, thank you for your amazing work!
I really want to check the result of the special condition picture on your network, but there is no available code to test, could you please support one? Like the [monodepth2](https://github.com/nianticlabs/monodepth2/blob/b676244e5a1ca55564eb5d16ab521a48f823af31/test_simple.py#L1-L171)

**Comment by Aradhye2002** [comment]
Hi thanks for showing interest in our work. We will be releasing the inference script soon.

**Comment by Aradhye2002** [comment]
Hi @wangjiyuan9, we have released the inference scripts. As a bonus, you can also convert videos to depth..
