### ISSUE TITLE
Predicted depth map only

### ISSUE THREAD

**Issue by jtsanborn1** [Aradhye2002/EcoDepth#7]
Is there a way to export a predicted depth map only instead of both image and its depth map side by side? Or/and even to save the grayscale depth map without color palette to the depth map.

Any argument to add to the lines?

**Comment by frankkim1108** [comment]
HI, @jtsanborn1
I was trying to do the same thing as you and I think I found a solution.

Add ` cv2.imwrite('../depth_map.png', depth_map)` to line 90 in infer.py file.
The writer of this code did `viz = np.hstack((img, depth_map))`, resulting the output to have both original image and depth map side by side.

**Comment by Aradhye2002** [comment]
Yes this is the correct way to proceed. Thanks @frankkim1108.

Closing as completed.
